
-- █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
-- █         Utilisation de la BD          █
-- █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█

USE Consumerism
GO



-- █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
-- █     Insertion de données dans les tables     █
-- █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█

-- nombre de données à insérer dans chaque table
EXEC sp_set_session_context 'max', 100
GO

-- obtient le nombre de rangees d'une table
IF OBJECT_ID('dbo.TABLESIZE') IS NOT NULL
  DROP FUNCTION dbo.TABLESIZE
GO

CREATE FUNCTION dbo.TABLESIZE(@tableName NVARCHAR(128))
RETURNS INT
AS
BEGIN
      DECLARE @count INT = (
            SELECT SUM([rows])
      FROM sys.partitions
      WHERE object_id=object_id(@tableName)
            AND index_id IN (0,1))
      RETURN @count
END
GO

-- equivalent de Math.max() en sql server
IF OBJECT_ID('dbo.MAX') IS NOT NULL
  DROP FUNCTION dbo.MAX
GO

CREATE FUNCTION dbo.MAX(@a INT, @b INT)
RETURNS INT
AS
BEGIN
      RETURN (SELECT 0.5 * ((@a + @b) + ABS(@a - @b)) )
END
GO

-- demand.bozo
DECLARE @names table (FirstName NVARCHAR(50),
      LastName NVARCHAR(50))
INSERT INTO @names
VALUES
      ('Theodore', 'LHeureux'),
      ('Valerie', 'Turgeon'),
      ('Chantal', 'Vallieres'),
      ('Lena', 'Handfield'),
      ('Zachary', 'Tanguay'),
      ('Kevin', 'Leduc'),
      ('Linus', 'Sebastian'),
      ('Matheo', 'Christine'),
      ('Geralt', 'Rivia'),
      ('Berke', 'Rentoul'),
      ('Lauren', 'Morecombe'),
      ('Vick', 'Macon'),
      ('Hubie', 'O''Gavin'),
      ('Ros', 'Conyers'),
      ('Cesaro', 'Maffey'),
      ('Robby', 'Wareing'),
      ('Denise', 'Goreisr'),
      ('Stanford', 'Panter'),
      ('Dimitry', 'Pinwill'),
      ('Aubrey', 'Girdlestone'),
      ('Dorey', 'Pitney'),
      ('Claire', 'Gamwell'),
      ('Elsi', 'Mackrill'),
      ('Ryley', 'Muirhead'),
      ('Kerry', 'Garvagh'),
      ('Chaddy', 'Larmouth'),
      ('Estele', 'Iffe'),
      ('Robby', 'Gavozzi'),
      ('Newton', 'Blowen'),
      ('Olympie', 'Ebdon'),
      ('Jarrad', 'Rubinovitsch'),
      ('Nell', 'Dimmick'),
      ('Dionne', 'Antecki'),
      ('Misha', 'McDowell'),
      ('Haven', 'Harbidge'),
      ('Amanda', 'Tunnow'),
      ('Tessy', 'Dumbarton'),
      ('Silvain', 'Martinelli'),
      ('Sabra', 'Tukely'),
      ('Baxter', 'Tellenbrok'),
      ('Ileane', 'Probyn'),
      ('Kristopher', 'Henri'),
      ('Siobhan', 'Proppers'),
      ('Alanah', 'MacNeish'),
      ('Clarabelle', 'Hollow'),
      ('Marcos', 'Baseley'),
      ('Michal', 'Mackleden'),
      ('Irwin', 'Enright'),
      ('Toma', 'Crab'),
      ('Codi', 'Illsley'),
      ('Jerry', 'Casa'),
      ('Lorna', 'Ormshaw'),
      ('Kathrine', 'Heimann'),
      ('Horatia', 'Paolacci'),
      ('Renelle', 'Onele'),
      ('Jobina', 'Longrigg'),
      ('Roger', 'Parnby'),
      ('Dorie', 'Calvert'),
      ('Agretha', 'Vallerine'),
      ('Juditha', 'Drinkale'),
      ('Aguistin', 'Pelosi'),
      ('Alanah', 'Wickins'),
      ('Agathe', 'Essery'),
      ('Pedro', 'Pardi'),
      ('Jaye', 'FitzGeorge'),
      ('Analise', 'Etchingham'),
      ('Hollie', 'Touret'),
      ('Judon', 'Bleeze'),
      ('Thom', 'Basilone'),
      ('Honoria', 'de Mendoza'),
      ('Marthe', 'Triswell'),
      ('Kimbell', 'Bridywater'),
      ('Farlay', 'Purchon'),
      ('Addi', 'Jiracek'),
      ('Gertrud', 'Basley'),
      ('Pauletta', 'Threadgold'),
      ('Onfroi', 'Sibborn'),
      ('Rodrique', 'Ell'),
      ('Malvina', 'Von Oertzen'),
      ('Duke', 'Hradsky'),
      ('Hilda', 'Dorcey'),
      ('Pen', 'Awcock'),
      ('Catriona', 'Boddis'),
      ('Rodolphe', 'Avramchik'),
      ('Pippy', 'Woollends'),
      ('Talya', 'Maddigan'),
      ('Nolie', 'Fleeming'),
      ('Rosalinda', 'Bortolozzi'),
      ('Paddy', 'Dowles'),
      ('Bartel', 'Hissett'),
      ('Marilyn', 'Cottrill'),
      ('Gayle', 'Megarry'),
      ('Johnathan', 'Durkin'),
      ('Jackqueline', 'Slatten'),
      ('Dredi', 'Pittendreigh'),
      ('Tabbi', 'Dennistoun'),
      ('Archer', 'Collum'),
      ('Briano', 'Harnott'),
      ('Ofilia', 'Pedlow'),
      ('Grenville', 'Downton'),
      ('Remington', 'Collie'),
      ('Tadd', 'Lavell'),
      ('Christian', 'Fellman'),
      ('Katya', 'Farron'),
      ('Tuckie', 'Jiruca'),
      ('Les', 'Solomonides'),
      ('Rupert', 'O''Heaney'),
      ('Sarette', 'Artz'),
      ('Zak', 'Ring'),
      ('Frank', 'Sirey'),
      ('Karen', 'Goater'),
      ('Mona', 'Earie'),
      ('Angeli', 'Wateridge'),
      ('Tarah', 'Rippen'),
      ('Jobina', 'Forrestall'),
      ('Maire', 'Barkhouse'),
      ('Fraze', 'Panther'),
      ('Benedick', 'Cranmore'),
      ('Mattheus', 'Avent'),
      ('Karen', 'Stracey'),
      ('Erv', 'Penddreth'),
      ('Eleanore', 'Almak'),
      ('Orion', 'Rickets'),
      ('Nichols', 'Stadding'),
      ('Chiquia', 'Rey'),
      ('Raquela', 'Muggleton'),
      ('Vere', 'Willison'),
      ('Darryl', 'Van'),
      ('Allyn', 'Enbury'),
      ('Talbert', 'Callingham'),
      ('Ernestus', 'Floyed'),
      ('Simona', 'Lissandri'),
      ('Roger', 'Webland'),
      ('Nevsa', 'Havvock'),
      ('Hestia', 'Byrkmyr'),
      ('Suellen', 'Dufoure'),
      ('Rickert', 'Verson'),
      ('Wolf', 'Stote'),
      ('Glyn', 'Teesdale'),
      ('Gaylor', 'Liccardo'),
      ('Nisse', 'Towner'),
      ('Laurel', 'Bulmer'),
      ('Symon', 'Albany'),
      ('Tull', 'Seydlitz'),
      ('Elena', 'Coffey'),
      ('Merci', 'Chance'),
      ('Rona', 'Soames'),
      ('Randolph', 'Stonelake'),
      ('Kit', 'Furmedge'),
      ('Peyter', 'Dolohunty'),
      ('Stacia', 'Hiland'),
      ('Olimpia', 'Stutely'),
      ('Joane', 'Robbeke'),
      ('Hortensia', 'Jiru'),
      ('Gwyn', 'Carine'),
      ('Cindie', 'Massot'),
      ('Alma', 'Dallicoat'),
      ('Arlana', 'Petzolt'),
      ('Leslie', 'Benge'),
      ('Elysha', 'Balthasar'),
      ('Grange', 'Darnborough'),
      ('Samson', 'Mongenot'),
      ('Alfredo', 'Rignall'),
      ('Lydia', 'Kirckman'),
      ('Nicola', 'Inglis'),
      ('Quincy', 'Braams'),
      ('Rafael', 'Quarrie'),
      ('Kingsly', 'Tuminelli'),
      ('Tammi', 'Pleaden'),
      ('Kelsey', 'Moulding'),
      ('Drusy', 'Hamil'),
      ('Maris', 'Dionis'),
      ('Bernie', 'Pacher'),
      ('Nigel', 'Volkers'),
      ('Lianna', 'Schohier'),
      ('Shaine', 'Kneal'),
      ('Lem', 'Challes'),
      ('Gertrud', 'Playfair'),
      ('Blakeley', 'Bindin'),
      ('Kaycee', 'Lamden'),
      ('Mikael', 'Bines'),
      ('Boothe', 'Phillips'),
      ('Grete', 'Peron'),
      ('Taylor', 'Andryushchenko'),
      ('Darla', 'Overshott'),
      ('Nolie', 'Kelley'),
      ('Stevana', 'Beverley'),
      ('Lorri', 'Briston'),
      ('Taryn', 'Hackleton'),
      ('Pammy', 'Gidman'),
      ('Giles', 'Poor'),
      ('Garth', 'Millimoe'),
      ('Marcie', 'Brawn'),
      ('Christine', 'Abella'),
      ('Layla', 'Vineall'),
      ('Ram', 'Yegorkov'),
      ('Davida', 'Leckenby'),
      ('Vinny', 'Gioan'),
      ('Blancha', 'Matzl'),
      ('Dorolisa', 'Toor'),
      ('Ly', 'Clerc'),
      ('Moshe', 'Spadazzi'),
      ('Quinton', 'Wilson'),
      ('Ruthie', 'Gallon'),
      ('Ulick', 'Bony'),
      ('Dannel', 'Gulliver'),
      ('Jeffry', 'Karpov'),
      ('Burty', 'Bartolomieu'),
      ('King', 'Crosetto'),
      ('Amabelle', 'Give'),
      ('Deck', 'McNeigh'),
      ('Mureil', 'Tumioto'),
      ('Wren', 'Donett'),
      ('Rolph', 'Wincer'),
      ('Morey', 'Pierro'),
      ('Damien', 'Eubank'),
      ('Andi', 'Ruzicka'),
      ('Katheryn', 'Djakovic'),
      ('Rycca', 'Cleiment'),
      ('Brady', 'Olivo'),
      ('Marsiella', 'Hanna'),
      ('Herculie', 'Graver'),
      ('Brena', 'Dinsell'),
      ('Svend', 'Hammerberger'),
      ('Betteann', 'Freeland'),
      ('Inge', 'Pleavin'),
      ('Brade', 'Schimaschke'),
      ('Gregor', 'Aubery'),
      ('Arri', 'Varey'),
      ('Penn', 'Paolucci'),
      ('Tim', 'Adamik'),
      ('Rutherford', 'Barroux'),
      ('Gus', 'Ruslin'),
      ('Kimball', 'Richfield'),
      ('Darcey', 'Fumagall'),
      ('Wilona', 'Sewter'),
      ('Ada', 'Dellenty'),
      ('Lucien', 'Fealey'),
      ('Camile', 'O''Coskerry'),
      ('Leese', 'MacNockater'),
      ('Wang', 'Trahear'),
      ('Deidre', 'Jorin'),
      ('Jory', 'Roberts'),
      ('Butch', 'Remirez'),
      ('Cecil', 'Woodyatt'),
      ('Dianne', 'Tunmore'),
      ('Nicholas', 'Archdeckne'),
      ('Eadmund', 'Bernetti'),
      ('Galvin', 'Schoroder'),
      ('Merry', 'Wheowall'),
      ('Nap', 'Cranage'),
      ('Gaby', 'Pollicote'),
      ('Derick', 'Cupitt'),
      ('Olwen', 'Frere'),
      ('Berri', 'Sorensen'),
      ('Avie', 'Joreau'),
      ('Garrett', 'Jakolevitch'),
      ('Hynda', 'Mulhill'),
      ('Selene', 'Lurner'),
      ('Gayelord', 'Acarson'),
      ('Kennan', 'Keoghane'),
      ('Frank', 'Cabell'),
      ('Corene', 'Close'),
      ('Averil', 'Jermyn'),
      ('Andie', 'Burdon'),
      ('Fielding', 'Chellam'),
      ('Dennet', 'Hunnywell'),
      ('Morgana', 'Attiwill'),
      ('Luise', 'Davidovici'),
      ('Marya', 'Waywell'),
      ('Kimmy', 'Hardy'),
      ('Zorine', 'Chapple'),
      ('Ettie', 'Isenor'),
      ('Lexine', 'Patershall'),
      ('Lani', 'Warwicker'),
      ('Ezechiel', 'Habercham'),
      ('Hurley', 'Villa'),
      ('Floria', 'Ord'),
      ('Farica', 'Crellin'),
      ('Caria', 'Fleckney'),
      ('Georges', 'Jemmison'),
      ('Wendye', 'Rashleigh'),
      ('Gaspard', 'Stoppe'),
      ('Pincas', 'Ironmonger'),
      ('Aimil', 'Moring'),
      ('Noellyn', 'Lantiff'),
      ('Iorgo', 'O'' Ronan'),
      ('Lindsay', 'Banham'),
      ('Luise', 'Crankhorn'),
      ('Joelynn', 'Franseco'),
      ('Catherine', 'Borne'),
      ('Calla', 'Fellon'),
      ('Arny', 'Strafen'),
      ('Etheline', 'Mc Ilwrick'),
      ('Antonino', 'Mateu'),
      ('Perren', 'Tetther'),
      ('Lonny', 'Roalfe'),
      ('Sibylle', 'McGreay'),
      ('Loren', 'Yon'),
      ('Deloris', 'Blanchette'),
      ('Marlie', 'Cabrer'),
      ('Aggie', 'Orsay'),
      ('Ashlan', 'Cusack'),
      ('Norrie', 'Fiddyment'),
      ('Ailene', 'Tine'),
      ('Gaultiero', 'MacFall'),
      ('Warden', 'Antognelli'),
      ('Wilbert', 'Lawty'),
      ('Camile', 'Skey'),
      ('Bastian', 'McCrachen'),
      ('Zsazsa', 'Weetch'),
      ('Brena', 'Yoodall'),
      ('Otho', 'Christie'),
      ('Alonso', 'Dawkins'),
      ('Rebeca', 'Norster'),
      ('Klemens', 'Gantlett'),
      ('Mireille', 'Fedorchenko'),
      ('Adella', 'Ferrino'),
      ('Maude', 'Bilyard'),
      ('Angeline', 'Varian'),
      ('Lilyan', 'Beaman'),
      ('Claire', 'Massei'),
      ('Rudd', 'Mutter'),
      ('Skipper', 'Pacheco'),
      ('Finley', 'Dudbridge'),
      ('Selie', 'Killough'),
      ('Hunfredo', 'Pearcy'),
      ('Tobe', 'Atwater'),
      ('Briant', 'Kingzeth'),
      ('Shellysheldon', 'Dawtrey'),
      ('Lira', 'Mulvin'),
      ('Kariotta', 'Leathem'),
      ('Beryl', 'Fielding'),
      ('Bibby', 'Learmonth'),
      ('Ceil', 'Hanshaw'),
      ('Sissie', 'Corden'),
      ('Darcy', 'Kennerknecht'),
      ('Antoine', 'McCarron'),
      ('Lindy', 'Bradnum'),
      ('Galen', 'Silk'),
      ('Lock', 'Burgoin'),
      ('Shannen', 'Peaurt'),
      ('Lucius', 'Dowle'),
      ('Bonnee', 'D''Adamo'),
      ('Oswald', 'Ravilus'),
      ('Gerard', 'Drew'),
      ('Ambrose', 'Swatton'),
      ('Cassey', 'Goodwyn'),
      ('Julius', 'Merwede'),
      ('Brent', 'Napolitano'),
      ('Pepillo', 'Bispham'),
      ('Davy', 'Smalls'),
      ('Tania', 'Wiersma'),
      ('Wendell', 'Austin'),
      ('Carlita', 'Merrgan'),
      ('Pall', 'Latus'),
      ('Ros', 'Ostrich'),
      ('Brigit', 'Titterington'),
      ('Eleanor', 'Comusso'),
      ('Nadine', 'Ong'),
      ('Kevan', 'Longson'),
      ('Persis', 'Guirard'),
      ('Katherina', 'Sacase'),
      ('Jemimah', 'Duling'),
      ('Ebba', 'Cahey'),
      ('Emalee', 'McMillian'),
      ('Basilius', 'Pitman'),
      ('Ozzie', 'Fattori'),
      ('Munroe', 'Poel'),
      ('Finlay', 'Wraighte'),
      ('Roxy', 'Sprionghall'),
      ('Candis', 'Van der Daal'),
      ('Jerrylee', 'Alelsandrovich'),
      ('Victoria', 'Silber'),
      ('Gerri', 'Tricker'),
      ('Hilliary', 'Hele'),
      ('Guinna', 'Northway'),
      ('Dana', 'Filipovic'),
      ('Tilda', 'Wyllie'),
      ('Flo', 'Lavrinov'),
      ('Cathlene', 'Daniau'),
      ('Humfrey', 'Geill'),
      ('Denys', 'Danihelka'),
      ('Seymour', 'Durtnel'),
      ('Melisent', 'Jelkes'),
      ('Catharina', 'Nansom'),
      ('Vally', 'Moreton'),
      ('Tommy', 'Mindenhall'),
      ('Packston', 'Bruty'),
      ('Jelene', 'Avrasin'),
      ('Ula', 'Oldham'),
      ('Myranda', 'Josupeit'),
      ('Babbette', 'Gavan'),
      ('Freddy', 'Gilchriest'),
      ('Ahmed', 'Feasley'),
      ('Toby', 'Braune'),
      ('Tull', 'Flint'),
      ('Krishnah', 'Faulconer'),
      ('Ruprecht', 'Wetherick'),
      ('Myrah', 'Rusling'),
      ('Albie', 'Bolesma'),
      ('Wang', 'Wellan'),
      ('Haley', 'Willingale'),
      ('Minne', 'Seathwright'),
      ('Fancy', 'Pelz'),
      ('Alair', 'Treadaway'),
      ('Nichole', 'Nickless'),
      ('Jenica', 'Patty'),
      ('Nancie', 'Fosse'),
      ('Rustin', 'Fladgate'),
      ('Franzen', 'Gazey'),
      ('Fredra', 'Slatter'),
      ('Floyd', 'Stoodley'),
      ('Ad', 'Hanscom'),
      ('Fletcher', 'Drewell'),
      ('Wash', 'Maundrell'),
      ('Cherida', 'Gingel'),
      ('Sam', 'Kielt'),
      ('Carmelina', 'Spillard'),
      ('Demott', 'Newrick'),
      ('Courtney', 'Allsobrook'),
      ('Worden', 'Stoade'),
      ('Monty', 'Gammack'),
      ('Leland', 'Sheehy'),
      ('Violette', 'Kerne'),
      ('Robin', 'Bonhan'),
      ('Konstance', 'Kinset'),
      ('Trixie', 'Heyburn'),
      ('Glenna', 'Burgne'),
      ('Trevar', 'Carpmile'),
      ('Maegan', 'Sinnett'),
      ('Sayre', 'Descroix'),
      ('Orelie', 'Tweed'),
      ('Iseabal', 'Erangey'),
      ('Krysta', 'Tappin'),
      ('Dacia', 'Eldin'),
      ('Theresa', 'Brothers'),
      ('Bastian', 'Petow'),
      ('Burtie', 'Bunt'),
      ('Carrissa', 'Mueller'),
      ('Kippar', 'Sagerson'),
      ('Wood', 'Rickets'),
      ('Kira', 'Gorelli'),
      ('Renaud', 'Minchi'),
      ('Matias', 'Lavrick'),
      ('Cora', 'Balchin'),
      ('Barbara-anne', 'Collick'),
      ('Roland', 'Rusbridge'),
      ('Nealon', 'Bartczak'),
      ('Claudell', 'Diglin'),
      ('Yolane', 'Halfhyde'),
      ('Curr', 'Hurll'),
      ('Clayborn', 'Lucio'),
      ('Cristiano', 'Boarleyson'),
      ('Gardie', 'McClean'),
      ('Bjorn', 'Nanetti'),
      ('Marian', 'Stayt'),
      ('Fulvia', 'Bilverstone'),
      ('Rosaline', 'Westwell'),
      ('Griselda', 'Petruska'),
      ('Missie', 'Bould'),
      ('Mallory', 'Giacomasso'),
      ('Brit', 'Fairhurst'),
      ('Heidi', 'Scollan'),
      ('Lalo', 'Fleetwood'),
      ('Jenn', 'Hancke'),
      ('Nobe', 'Caras'),
      ('Darrel', 'Onthank'),
      ('Nanni', 'Cranmere'),
      ('Ellen', 'Di Bernardo'),
      ('Sibilla', 'Van Arsdall'),
      ('Daryn', 'Nelane'),
      ('Ellis', 'Drinnan'),
      ('Tripp', 'Kyncl'),
      ('Kara', 'Badgers'),
      ('Phillie', 'Stoppard'),
      ('Benita', 'Cousin'),
      ('Janenna', 'Olver'),
      ('Kathlin', 'Bromhead'),
      ('Corette', 'Mac'),
      ('Kellie', 'Nestoruk'),
      ('Dot', 'Cooper'),
      ('Loraine', 'Kobera'),
      ('Zorine', 'McGavigan'),
      ('Kliment', 'Pickthorne'),
      ('Sidonia', 'Wardell'),
      ('Dare', 'Geraldez'),
      ('Angy', 'Woollam'),
      ('Pinchas', 'Morfey'),
      ('Inessa', 'Coniam'),
      ('Hugibert', 'Swenson'),
      ('Ninette', 'Chaplain'),
      ('Laney', 'Stanyland'),
      ('Tammara', 'Dable'),
      ('Dorella', 'Pachta'),
      ('Emory', 'Butterly'),
      ('Mildred', 'Everist'),
      ('Janine', 'Rodda'),
      ('Bettina', 'Renzini'),
      ('Benoite', 'O''Flaverty'),
      ('Sascha', 'Swancock'),
      ('Freddie', 'Dmitrievski'),
      ('Ahmad', 'Cozby'),
      ('Eamon', 'Duckit'),
      ('Julia', 'Egalton'),
      ('Chauncey', 'Craigheid'),
      ('Loy', 'Gait'),
      ('Inness', 'Yardley'),
      ('Celisse', 'Dinning'),
      ('Lynnette', 'Edling'),
      ('Vida', 'Lutty'),
      ('Kristel', 'Tupper'),
      ('Parrnell', 'Bowick'),
      ('Stephanus', 'Opy'),
      ('Eda', 'Inns'),
      ('Cory', 'Wilprecht'),
      ('Natalie', 'Darth'),
      ('Pavel', 'Chippindale'),
      ('Roxanna', 'Gold'),
      ('Nicoli', 'Hansom'),
      ('Dolph', 'Utterson'),
      ('Tyson', 'O''Spellissey'),
      ('Kandace', 'Massingham'),
      ('Filip', 'Aliberti'),
      ('Adora', 'Baseke'),
      ('Margalo', 'Hunnawill'),
      ('Cory', 'Henryson'),
      ('Shaine', 'Haile'),
      ('Frederik', 'Cox'),
      ('Hercule', 'Russel'),
      ('Caroljean', 'Gymlett'),
      ('Sarajane', 'Ansett'),
      ('Anica', 'Habberjam'),
      ('Woodie', 'MacGebenay'),
      ('Idaline', 'Hawgood'),
      ('Nowell', 'Meeke'),
      ('Gearalt', 'Ebbles'),
      ('Franky', 'Paddell'),
      ('Monro', 'Degue'),
      ('Lindie', 'Jeste'),
      ('Jessamine', 'Saterweyte'),
      ('Marquita', 'Breede'),
      ('Edithe', 'Greeveson'),
      ('Cosimo', 'Rumsby'),
      ('Cherey', 'Mazin'),
      ('Zora', 'Burney'),
      ('Teresa', 'Egdale'),
      ('Maud', 'Buttrum'),
      ('Zebulen', 'Markussen'),
      ('Ravid', 'Llewelly'),
      ('Lonnie', 'Folini'),
      ('Devora', 'MacKibbon'),
      ('Theresina', 'Cutajar'),
      ('Wilma', 'Fripp'),
      ('Simeon', 'Osmar'),
      ('Gwenny', 'Haggata'),
      ('Jerrome', 'Ferres'),
      ('Renato', 'Bockmann'),
      ('Biddy', 'Wenman'),
      ('Gav', 'Rings'),
      ('Shay', 'Miller'),
      ('Cristina', 'Hartwell'),
      ('Joane', 'Dohmann'),
      ('Iolanthe', 'Wreath'),
      ('Maurise', 'Piesing'),
      ('Diena', 'Reggiani'),
      ('Aymer', 'Benfield'),
      ('Nichols', 'Fronzek'),
      ('Clari', 'Loughney'),
      ('Washington', 'Fletcher'),
      ('Cesare', 'Trewinnard'),
      ('Rabbi', 'Harron'),
      ('Rogerio', 'Tenant'),
      ('Audrey', 'Sutherington'),
      ('Kermie', 'Klassman'),
      ('Rodi', 'Lembcke'),
      ('Bastien', 'Limon'),
      ('Perri', 'Meaden'),
      ('Erich', 'Hardwicke'),
      ('Suzi', 'Folley'),
      ('Enrica', 'Lenham'),
      ('Aurel', 'Brumwell'),
      ('Krisha', 'Ortell'),
      ('Wandis', 'Offill'),
      ('Edeline', 'Lode'),
      ('Barbie', 'Scarfe'),
      ('Jacinda', 'Midgely'),
      ('Cullan', 'Menichini'),
      ('Dyan', 'Armitt'),
      ('Ingemar', 'Whatley'),
      ('Jacquenette', 'Grigore'),
      ('Daria', 'Rheam'),
      ('Dmitri', 'Bamb'),
      ('Nona', 'Ondrich'),
      ('Zahara', 'Dulton'),
      ('Thoma', 'Paulsen'),
      ('Veronica', 'Romke'),
      ('Esme', 'Birdwhistell'),
      ('Jarrid', 'Reboulet'),
      ('Rubi', 'Beavington'),
      ('Caitlin', 'Thurgood'),
      ('Stafani', 'Hoy'),
      ('Lindon', 'Fontin'),
      ('Brooks', 'Deaton'),
      ('Garner', 'Wavell'),
      ('Vin', 'Lening'),
      ('Fanchon', 'Sexon'),
      ('Inessa', 'Battyll'),
      ('Sid', 'Ronchka'),
      ('Christophorus', 'Lamp'),
      ('Wilmer', 'Bartley'),
      ('Breanne', 'Piddick'),
      ('Nathalie', 'Boater'),
      ('Sacha', 'Tottem'),
      ('Bird', 'Claque'),
      ('Kerry', 'Ferrieroi'),
      ('Rhea', 'Boggis'),
      ('Giusto', 'Tantrum'),
      ('Arin', 'Evers'),
      ('Nowell', 'Freddi'),
      ('Cordey', 'Blaker'),
      ('Gail', 'Wooler'),
      ('Brita', 'Spancock'),
      ('Aurore', 'Sybe'),
      ('Gardener', 'Sinden'),
      ('Alisander', 'Saunier'),
      ('Miquela', 'Goneau'),
      ('Brien', 'Leavold'),
      ('Miquela', 'Cuerdale'),
      ('Hercule', 'Herion'),
      ('Buffy', 'Baptiste'),
      ('Esra', 'Stanworth'),
      ('Dianemarie', 'Nisuis'),
      ('Chiquia', 'Stocks'),
      ('Katey', 'Valde'),
      ('Bobina', 'McIndrew'),
      ('Herbie', 'Fernandez'),
      ('Klement', 'Dabs'),
      ('Patton', 'Brunnen'),
      ('Boote', 'Revan'),
      ('Dorie', 'Haughin'),
      ('Gunther', 'Duchasteau'),
      ('Adel', 'Pearch'),
      ('Guillaume', 'Tows'),
      ('Pernell', 'Borgesio'),
      ('Andrea', 'Lumber'),
      ('Jess', 'Burndred'),
      ('Giustino', 'Bubbins'),
      ('Herschel', 'Corran'),
      ('Rhianna', 'Bollard'),
      ('Olga', 'Shingfield'),
      ('Carter', 'Howles'),
      ('Augy', 'O''Suaird'),
      ('Clo', 'Heckner'),
      ('Brittani', 'Hazlewood'),
      ('Abigail', 'Breckell'),
      ('Noll', 'Gladeche'),
      ('Fayre', 'Gilhouley'),
      ('Natividad', 'Fance'),
      ('Sharity', 'Charker'),
      ('Christy', 'Barz'),
      ('Martita', 'Razoux'),
      ('Mitchel', 'Cunningham'),
      ('Gwenny', 'Ebbens'),
      ('Nesta', 'Yare'),
      ('Dasie', 'Jelf'),
      ('Darby', 'O''Howbane'),
      ('Dorisa', 'Merchant'),
      ('Aurea', 'Sansom'),
      ('Catlee', 'Mcettrick'),
      ('Elliot', 'Drummer'),
      ('Madalyn', 'McCreadie'),
      ('Tracie', 'Botterill'),
      ('Hobey', 'Adcock'),
      ('Alexandr', 'Skene'),
      ('Aleece', 'Dahmke'),
      ('Flemming', 'Martineau'),
      ('Dorita', 'Hamer'),
      ('Thelma', 'Croke'),
      ('Kit', 'Ragsdall'),
      ('Roderic', 'Pippin'),
      ('Brantley', 'Bark'),
      ('Nickey', 'Camous'),
      ('Boyce', 'Luebbert'),
      ('Chad', 'D''Onisi'),
      ('Brande', 'Osborne'),
      ('Lothaire', 'Chicchetto'),
      ('Angelle', 'Vauter'),
      ('Mimi', 'Yeardsley'),
      ('Marline', 'Solman'),
      ('Eunice', 'Ferminger'),
      ('Robby', 'Hamsley'),
      ('Kirstin', 'Costellow'),
      ('Guinevere', 'Raithmill'),
      ('Nan', 'Muddiman'),
      ('Alvis', 'Edlin'),
      ('Moira', 'Ivy'),
      ('Cleo', 'Stower'),
      ('Natala', 'Reace'),
      ('Nerta', 'Jewis'),
      ('Cleveland', 'Kildea'),
      ('Etti', 'Jikylls'),
      ('Nissa', 'Lightoller'),
      ('Jonas', 'Coleshill'),
      ('Eden', 'Truwert'),
      ('Allina', 'Ghilks'),
      ('Kaiser', 'Inglese'),
      ('Weber', 'Kempstone'),
      ('Rafaelita', 'Mealing'),
      ('Waylen', 'Allman'),
      ('Jeno', 'McHaffy'),
      ('Avril', 'Cianelli'),
      ('Tabatha', 'Feaver'),
      ('Dorice', 'Nardi'),
      ('Vivianne', 'Chidlow'),
      ('Arthur', 'Leat'),
      ('Michaella', 'Mosby'),
      ('Dar', 'Winspar'),
      ('Lynda', 'Jorgensen'),
      ('Thorpe', 'Spiniello'),
      ('Gwendolyn', 'McAlindon'),
      ('Gerianne', 'Banes'),
      ('Rafaellle', 'Bartolomieu'),
      ('Winne', 'Ambage'),
      ('Stearn', 'Hiddsley'),
      ('Derron', 'Cropton'),
      ('Robert', 'Faraday'),
      ('Kayla', 'Elliott'),
      ('Willdon', 'Rosser'),
      ('Jaquelin', 'Giorgietto'),
      ('Hayley', 'Whilder'),
      ('Danita', 'O''Rodane'),
      ('Matthieu', 'Maskell'),
      ('Elvera', 'Lambert-Ciorwyn'),
      ('Audre', 'Leger'),
      ('Alverta', 'Hooban'),
      ('Emmet', 'Staddon'),
      ('Isaiah', 'De Wolfe'),
      ('Frederique', 'Danett'),
      ('Jonathon', 'Prime'),
      ('Anna-diana', 'Ginity'),
      ('Con', 'Spillman'),
      ('Eyde', 'Le Moucheux'),
      ('Debee', 'Wonham'),
      ('Cordie', 'Trevance'),
      ('Gray', 'Adelsberg'),
      ('Donni', 'Peterken'),
      ('Pooh', 'Seeler'),
      ('Rutger', 'Jacmard'),
      ('Cam', 'Seifenmacher'),
      ('Winnie', 'Tarpey'),
      ('Cayla', 'Boulter'),
      ('Luci', 'Slesser'),
      ('Odelle', 'Victor'),
      ('Ettie', 'Oles'),
      ('Borden', 'Aldham'),
      ('Tracey', 'Rentcome'),
      ('Emmet', 'Dewick'),
      ('Lyda', 'Petrov'),
      ('Augusto', 'Plume'),
      ('Liane', 'Chedzoy'),
      ('Bennie', 'McGorley'),
      ('Morse', 'Blancowe'),
      ('Sascha', 'Arends'),
      ('Nissie', 'Pablo'),
      ('Ranee', 'Woodroofe'),
      ('Isadora', 'Scogin'),
      ('Chrisse', 'Millberg'),
      ('Alicea', 'Pleager'),
      ('Ezequiel', 'Glasspoole'),
      ('Rafa', 'Crunkhurn'),
      ('Jenny', 'Mimmack'),
      ('Amie', 'Hamer'),
      ('Tyne', 'Donovan'),
      ('Baryram', 'Mignot'),
      ('Mitzi', 'Knutton'),
      ('Essy', 'Kubatsch'),
      ('Gothart', 'Hynam'),
      ('Rozalie', 'Thornewell'),
      ('Othello', 'Godar'),
      ('Maura', 'Brosh'),
      ('Ethel', 'Geekie'),
      ('Florance', 'Serrels'),
      ('Almire', 'Mendez'),
      ('Wanids', 'Esler'),
      ('Adam', 'Lewry'),
      ('Ceil', 'Santer'),
      ('Judy', 'Pepper'),
      ('Costa', 'Blackmoor'),
      ('Krystalle', 'Winyard'),
      ('Georgie', 'Minster'),
      ('Lombard', 'Coulbeck'),
      ('Ardith', 'Jeste'),
      ('Cobb', 'Patchett'),
      ('Vivian', 'Milward'),
      ('Daisie', 'Walch'),
      ('Ozzy', 'Samudio'),
      ('Cornela', 'MacAndie'),
      ('Dennet', 'Cantos'),
      ('Mickie', 'Duligall'),
      ('Chandal', 'Ruger'),
      ('Joelynn', 'Verillo'),
      ('Neil', 'Drews'),
      ('Darrell', 'Firsby'),
      ('Lonna', 'Perazzo'),
      ('Fredi', 'Breckwell'),
      ('Faustine', 'Farriar'),
      ('Alejandra', 'Chomicki'),
      ('Datha', 'Kohlerman'),
      ('Stephi', 'Cressar'),
      ('Allie', 'Laver'),
      ('Fannie', 'Gooderham'),
      ('Shanna', 'Yurmanovev'),
      ('Lena', 'Costar'),
      ('Larine', 'Rosewell'),
      ('Halsy', 'Blanch'),
      ('Ema', 'Southard'),
      ('Zorah', 'Pegden'),
      ('Shalna', 'Jaffra'),
      ('Larine', 'Cordero'),
      ('Valene', 'Lunk'),
      ('Twyla', 'Tooth'),
      ('Noami', 'Radborne'),
      ('Clayson', 'Chick'),
      ('Felic', 'Waleran'),
      ('Herrick', 'Wraighte'),
      ('Alexi', 'McNern'),
      ('Thane', 'O''Lenane'),
      ('Ricard', 'Brussels'),
      ('Johanna', 'Brittlebank'),
      ('Tucker', 'Gawler'),
      ('Hill', 'Colquete'),
      ('Filippa', 'Dulake'),
      ('Emalia', 'Lindenstrauss'),
      ('Lorens', 'Handscombe'),
      ('Alvin', 'Dradey'),
      ('Mellisent', 'Millions'),
      ('Guilbert', 'Rochford'),
      ('Sadie', 'Clemitt'),
      ('Birch', 'Atterley'),
      ('Garnette', 'Givens'),
      ('Evania', 'Fass'),
      ('Lita', 'Swains'),
      ('Mort', 'Barbisch'),
      ('Ivonne', 'Thornton'),
      ('Robbie', 'Lathe'),
      ('Janot', 'Kornyakov'),
      ('Imogene', 'Krates'),
      ('Adele', 'Lismer'),
      ('Kaila', 'Winning'),
      ('Clay', 'Lockless'),
      ('Lynna', 'Ferns'),
      ('Kari', 'Camilleri'),
      ('Lurlene', 'Matuszynski'),
      ('Dare', 'Uttermare'),
      ('Dorothee', 'Stampe'),
      ('Bernette', 'Errichiello'),
      ('Leo', 'Cicculi'),
      ('Kym', 'Itzig'),
      ('Iggie', 'McKillop'),
      ('Panchito', 'Guilfoyle'),
      ('Chen', 'Rosling'),
      ('Kareem', 'Edis'),
      ('Johny', 'Burgess'),
      ('Anita', 'Riby'),
      ('Claudia', 'Harlett'),
      ('Ted', 'Gladdin'),
      ('Deirdre', 'Heigho'),
      ('Basilio', 'Kell'),
      ('Alfie', 'Mazzilli'),
      ('Rani', 'Rustedge'),
      ('Barbara-anne', 'Donet'),
      ('Leah', 'Chat'),
      ('Edwina', 'Gearty'),
      ('Francklin', 'Murcott'),
      ('Hillard', 'Taffurelli'),
      ('Doti', 'Blanshard'),
      ('Bart', 'McDunlevy'),
      ('Marybeth', 'Abrahim'),
      ('Alfons', 'Thome'),
      ('Thorvald', 'Shelmardine'),
      ('Staffard', 'Blazey'),
      ('Siobhan', 'Lownds'),
      ('Georgine', 'Mowne'),
      ('Evelina', 'Flawith'),
      ('Bab', 'Fernan'),
      ('Larry', 'Ohrt'),
      ('Augustus', 'Catlin'),
      ('Dyna', 'Morican'),
      ('Stinky', 'Pooke'),
      ('Elise', 'Brann'),
      ('Dalston', 'Fellgett'),
      ('Avery', 'Garroway'),
      ('Bab', 'Kyrkeman'),
      ('Whitney', 'Trencher'),
      ('Kathye', 'Francois'),
      ('Ricard', 'Busfield'),
      ('Shermy', 'Brocklebank'),
      ('Katy', 'Helgass'),
      ('Brynn', 'Chezier'),
      ('Rodge', 'Pressnell'),
      ('Alika', 'Smalls'),
      ('Sherill', 'Houndesome'),
      ('Fania', 'Emm'),
      ('Alison', 'Lovitt'),
      ('Fransisco', 'Chesney'),
      ('Kaylil', 'Montague'),
      ('Sheelah', 'Turbill'),
      ('Fabiano', 'Bedberry'),
      ('Fenelia', 'Nealand'),
      ('Keriann', 'Penketh'),
      ('Christan', 'Littefair'),
      ('Cindy', 'Caruth'),
      ('Delia', 'Gossling'),
      ('Chlo', 'McKelvey'),
      ('Eolanda', 'Tremoille'),
      ('Mendie', 'Fones'),
      ('Marius', 'Wigley'),
      ('Ara', 'Varlow'),
      ('Brian', 'Piscopo'),
      ('Elvina', 'Rebichon'),
      ('Carmelia', 'Flye'),
      ('Jeremie', 'Doubleday'),
      ('Wini', 'Leslie'),
      ('Mirabel', 'Yule'),
      ('Georgi', 'Beinisch'),
      ('Orrin', 'Manginot'),
      ('Lucio', 'Chatelot'),
      ('Farlay', 'Zorener'),
      ('Leena', 'Fettes'),
      ('Chelsie', 'Shakspeare'),
      ('Shepard', 'Seagrave'),
      ('Abeu', 'Mainwaring'),
      ('Bonny', 'Ervine'),
      ('Galen', 'Trenear'),
      ('Osbourn', 'Conway'),
      ('Ethelin', 'Belk'),
      ('Melva', 'McGahey'),
      ('Lyman', 'Swaton'),
      ('Charisse', 'Fenby'),
      ('Bel', 'Iffe'),
      ('Adolpho', 'Hallward'),
      ('Mamie', 'Motion'),
      ('Chad', 'Carlin'),
      ('Brena', 'Soars'),
      ('Lind', 'McGillreich'),
      ('Vera', 'Babbs'),
      ('Nikolas', 'Brandenburg'),
      ('Stephanie', 'Thorouggood'),
      ('Eolanda', 'Rustedge'),
      ('Saw', 'Wison'),
      ('Prent', 'Mengo'),
      ('Findley', 'Folbigg'),
      ('Sybil', 'Stickels'),
      ('Aland', 'Mayler'),
      ('Justine', 'Corson'),
      ('Vivyan', 'Buntin'),
      ('Jan', 'Papa'),
      ('Kylie', 'Waberer'),
      ('Garvey', 'Richichi'),
      ('Jarrod', 'Tomaselli'),
      ('Hartwell', 'Mattingly'),
      ('Murdoch', 'Reuss'),
      ('Diena', 'Aire'),
      ('Magnum', 'Diemer'),
      ('Si', 'Rockell'),
      ('Lexy', 'Beacock'),
      ('Aubine', 'Ridge'),
      ('Haily', 'Heild'),
      ('Garvy', 'Jachimiak'),
      ('Catlee', 'Hewins'),
      ('Cary', 'Damiata'),
      ('Sebastian', 'Melbourne'),
      ('Simon', 'Robuchon'),
      ('Alyce', 'Guerrier'),
      ('Guglielma', 'Woolforde'),
      ('Howie', 'Jore'),
      ('Paola', 'Clother'),
      ('Roda', 'MacLese'),
      ('Adan', 'Newby'),
      ('Koressa', 'Khristyukhin'),
      ('Whitby', 'Scarman'),
      ('Mandi', 'Eslie'),
      ('Inger', 'Simonite'),
      ('Brook', 'Bridat'),
      ('Beverlie', 'Tointon'),
      ('Barde', 'Dennant'),
      ('Dennis', 'Yersin'),
      ('Eli', 'Benediktovich'),
      ('Stu', 'Fowley'),
      ('Riane', 'Kinver'),
      ('Alair', 'Bransom'),
      ('Annabelle', 'Rate'),
      ('Arvin', 'Vankov'),
      ('Bennie', 'Brody'),
      ('Fawne', 'Sharvell'),
      ('Jennee', 'Doerling'),
      ('Mathilda', 'Carnier'),
      ('Lewiss', 'Jorioz'),
      ('Ronalda', 'Desaur')






DECLARE @i INT = dbo.TABLESIZE(N'Demand.Bozo')
DECLARE @max INT = @i + CONVERT(INT, SESSION_CONTEXT(N'max'))
WHILE @i < @max
BEGIN
      INSERT INTO Demand.Bozo
      VALUES
            (
                  (SELECT TOP 1 FirstName FROM @names ORDER BY NEWID()),
                  (SELECT TOP 1 LastName FROM @names ORDER BY NEWID()),
                  NEWID(),
                  RAND() * 100
      )
      SET @i = @i + 1
END
PRINT 'Insertion des BOZOS terminée.'
GO

-- offer.enterprise
DECLARE @i INT = dbo.TABLESIZE(N'Offer.Enterprise')
DECLARE @max INT = @i + CONVERT(INT, SESSION_CONTEXT(N'max'))
WHILE @i < @max
BEGIN
      INSERT INTO Offer.Enterprise
      VALUES
            (
                  'Name ' + LTRIM(@i),
                  DATEADD(DAY, RAND() * 1000, '2000-01-01')
      )
      SET @i = @i + 1
END
PRINT 'Insertion des ENTREPRISES terminée.'
GO

-- offer.contract
DECLARE @i INT = dbo.TABLESIZE(N'Offer.Contract')
DECLARE @max INT = @i + CONVERT(INT, SESSION_CONTEXT(N'max'))
WHILE @i < @max
BEGIN
      INSERT INTO Offer.Contract
      VALUES
            (
                  'Description ' + LTRIM(@i),
                  RAND() * 100,
                  dbo.MAX(1, RAND() * @max),
                  dbo.MAX(1, RAND() * @max)
      )
      SET @i = @i + 1
END
PRINT 'Insertion des CONTRATS terminée.'
GO

-- offer.production
DECLARE @i INT = dbo.TABLESIZE(N'Offer.Production')
DECLARE @max INT = @i + CONVERT(INT, SESSION_CONTEXT(N'max'))
WHILE @i < @max
BEGIN
      INSERT INTO Offer.Production
      VALUES
            (
                  DATEADD(DAY, RAND() * 1000, '2000-01-01T00:00:00'),
                  RAND() * 100000,
                  dbo.MAX(1, RAND() * @max)
      )
      SET @i = @i + 1
END
PRINT 'Insertion des PRODUCTIONS terminée.'
GO

-- offer.product
DECLARE @i INT = dbo.TABLESIZE(N'Offer.Product')
DECLARE @max INT = @i + CONVERT(INT, SESSION_CONTEXT(N'max'))
WHILE @i < @max
BEGIN
      INSERT INTO Offer.Product
      VALUES
            (
                  'Name ' + LTRIM(@i),
                  (CASE WHEN RAND() < 0.5 THEN 1 ELSE 0 END),
                  RAND() * 1000000,
                  RAND() * 100
      )
      SET @i = @i + 1
END
PRINT 'Insertion des PRODUITS terminée.'
GO

-- offer.productinstance
DECLARE @i INT = dbo.TABLESIZE(N'Offer.ProductInstance')
DECLARE @max INT = @i + CONVERT(INT, SESSION_CONTEXT(N'max'))
WHILE @i < @max
BEGIN
      INSERT INTO Offer.ProductInstance
      VALUES
            (
                  dbo.MAX(1, RAND() * @max),
                  dbo.MAX(1, RAND() * @max)
      )
      SET @i = @i + 1
END
PRINT 'Insertion des INSTANCES DE PRODUITS terminée.'
GO

-- demand.transaction
DECLARE @i INT = dbo.TABLESIZE(N'Demand.Transaction')
DECLARE @max INT = @i + CONVERT(INT, SESSION_CONTEXT(N'max'))
WHILE @i < @max
BEGIN
      INSERT INTO Demand.[Transaction]
      VALUES
            (
                  DATEADD(DAY, RAND() * 1000, '2000-01-01'),
                  RAND() * 1000000,
                  dbo.MAX(1, RAND() * @max),
                  dbo.MAX(1, RAND() * @max),
                  dbo.MAX(1, RAND() * @max)
      )
      SET @i = @i + 1
END
PRINT 'Insertion des TRANSACTIONS terminée.'
GO

PRINT 'Nous avons généré ' + CONVERT(varchar(50), SESSION_CONTEXT(N'max')) + ' données par table.'

-- afficher les résultats
EXEC sp_MSForEachTable 'exec sp_spaceused [?]'